name: Upload to Heroku
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Heroku
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: "camerlynck.michael@outlook.com"
          heroku_app_name: "themepark-r0831153"
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-Path pom.xml| Should -Be $true

